name: Release Deploy

on:
  workflow_dispatch: 
    inputs: 
      tag-version: 
        description: Tag Version in form of MAJOR.MINOR.VERSION like 1.0.0
        required: true
      env: 
        description: environment to deploy uat or prod 
        required: true

jobs: 
  release-deploy:
    runs-on: ubuntu-latest
    if:  ${{ inputs.tag-version }} 
    environment: ${{ inputs.env }}
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
      - name: Cache dependencies
        uses: actions/cache@v3.3.2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 8
      - name: Clean and Compile with Maven
        env: 
          TAG_VERSION: ${{ inputs.tag-version }}
        run: |
          echo "$TAG_VERSION"
          git checkout "tags/$TAG_VERSION"
