name: Dev Deploy
run-name: Dev Build and Deployment

on:
  push:
    branches: [ feature/* ] 

jobs:
  build-dev:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 8
      - name: Clean with Maven
        run: mvn clean compile 
      - name: Run Munit tests 
        run: mvn test
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Upload artifact 
        uses: actions/upload-artifact@v3
        with:
            name: artifacts
            path: target/*.jar 
      - name: Deploy to Dev environment 
        env:
          USERNAME: ${{ secrets.anypoint_platform_username }}
          PASSWORD: ${{ secrets.anypoint_platform_password }}
        run: |
          artifactName=$(ls *.jar | head -1)
          mvn deploy -DmuleDeploy \
           -Dmule.artifact=$artifactName \
           -Danypoint.username="$USERNAME" \
           -Danypoint.password="$PASSWORD" 

