name: Qa Release
run-name: Qa Release and Tagging

on:
  push:
    branches: [ qa ] 

jobs:
  build-release-qa:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
      - name: Cache dependencies
        uses: actions/cache@v3.3.2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 8
      - name: Clean with Maven
        run: mvn clean compile 
      - name: Run Munit tests 
        run: mvn test
      - name: Remove SNAPSHOT and prepare release and tag the release
        run: mvn versions:set -DremoveSnapshot
      - name: Compile and Test the project 
        run: |
          mvn clean compile -U
          mvn test -Denv=sit 
      - name: Extract the POM version 
        id: retrieve-pom-version
        run: |
          mvn help:evaluate -Dexpression=project.version -q -DforceStdout >> $GITHUB_OUTPUT
          echo "POM_VERSION=$GITHUB_OUTPUT" >> $GITHUB_OUTPUT  
      - name: Tag the release and commit/push changes to remote repository
        env: 
          POM_VERSION: ${{ steps.retrieve-pom-version.outputs.POM_VERSION }}
        run: |
          echo "$POM_VERSION"
