name: Deploy a Release to Uat
run-name: Deploying a Release tag to Uat environment

on:
  workflow_dispatch:
    inputs: 
      tags:
        description: "Release tag version in MAJOR.MINOR.PATCH version format, for ex: 1.0.0"
        required: true
        type: string

jobs:
  release-uat:
    runs-on: ubuntu-latest
    if:  ${{ inputs.tags }} 
    environment: uat
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
      - name: Cache dependencies
        uses: actions/cache@v3.3.2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 8
      - name: Clean and Compile with Maven
        env: 
          TAG_VERSION: ${{ inputs.tags }}
        run: |
          echo "$TAG_VERSION"
          git checkout "tags/$TAG_VERSION"
          mvn clean compile 
